model:
  name         : blstm
  epochs       : 100
  batch_size   : 128
  hidden_units : 100
  gpu_count    : 1    

S3:
  bucket_name     : production-enrichment-repo
  folder:           blstm
  tokenizer_name  : blstm.json
  training_params : training_params.pkl
  data_path       : cleartext_passwords.csv
  history_pkl     : history.pkl

data:
  path: '../data/dump.csv'